services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3004:3004"
    volumes:
      - gdata:/home/node/app/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    depends_on:
      - app
    environment:
      - TUNNEL_ORIGIN_PORT=3004

volumes:
  gdata:
